name: recipes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.2.0
  firebase_messaging: ^15.1.2

  # Notifications
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.0

  shared_preferences: ^2.2.2
